backend: 
  name: github 
  branch: master
  repo: osogrizz/mona-lisa

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "images"

collections:
  - label: "BookItems"
    name: "book-items"
    folder: "src/items"
    createdAT: 
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Image", name: "thumbnail", widget: "image", required: true }
      - {label: "Title", name: "title", widget: "string", required: true }
      - {label: "Author", name: "author", widget: "string", required: true }
      - {label: "Description", name: "description", widget: "string", required: false }
      - {label: "Price", name: "price", widget: "string", required: true }
      - {label: "imbd", name: "imdb", widget: "string", required: true }
      - {label: "Publish Date", name: "date", widget: "datetime"}